# Generated by Django 5.2.4 on 2025-07-16 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.TextField()),
                ('street_name', models.TextField()),
                ('country', models.TextField()),
                ('state', models.TextField()),
                ('pin', models.IntegerField()),
                ('city', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='addresses/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.form')),
            ],
        ),
    ]
